### ISSUE TITLE
Incorrect method_id definition for events ABI

### ISSUE THREAD

**Issue by k1rill-fedoseev** [poanetwork/ex_abi#156]
ABI spec stores full 32-byte event selectors in `topic0` - https://docs.soliditylang.org/en/v0.8.23/abi-spec.html#events, which is a slightly different behavior than the 4-byte selectors used for methods and errors.

Using shorter 4-byte event ids for event signature matching is error-prone and can lead to unnecessary collisions:
```
$ cast sig 'Transfer(address,address,uint256)'                              
0xddf252ad
$ cast sig 'BeckerrJon(bytes16,bytes4,bytes23,bytes16,bytes1,bytes7,bytes1)'
0xddf252ad
$ cast sig-event 'Transfer(address,address,uint256)'                        
0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef
$ cast sig-event 'BeckerrJon(bytes16,bytes4,bytes23,bytes16,bytes1,bytes7,bytes1)'
0xddf252ade8bdc6f18de3868ae50ab6e67ee261b7136b3141cd791f1ad4786a79
```

At last, 4-byte `method_id` definition in `FunctionSelector` struct does not make a lot of sense for events, a full 32-byte selector would be more useful in practice.

**Comment by ayrat555** [comment]
@k1rill-fedoseev sorry for the late reply. I missed this issue. 

do you know what is the behaviour of https://web3js.readthedocs.io/en/v1.2.11/web3-eth-abi.html ? do they store 4 or 32 bytes?

**Comment by k1rill-fedoseev** [comment]
Web3js parses event signatures as 32 bytes - https://web3js.readthedocs.io/en/v1.2.11/web3-eth-abi.html#encodeeventsignature
They also use full 32-byte signatures for log parsing and decoding
