### ISSUE TITLE
encoding of multiple dynamic size arrays is incorrect

### ISSUE THREAD

**Issue by seamon** [poanetwork/ex_abi#26]
`ABI.encode("test(uint[], uint[])", [[1], [2]]) |> Base.encode16(case: :lower)`

we got

"f0d7f6eb00000000000000000000000000000000000000000000000000000000000000 `6` 000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002"

but web3js generates:

"f0d7f6eb00000000000000000000000000000000000000000000000000000000000000 `4` 000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002"

look at the numbers emphasized, one is `6`, the other one is `4`.

it looks like a problem, cause when i send the transaction, it fails and reverted on "Error encountered".

thank you so much

**Comment by InoMurko** [comment]
hi @seamon which version is this?

**Comment by seamon** [comment]
the latest version, 0.3.0.

in my mix.exs:

{:ex_abi, github: "poanetwork/ex_abi"}

**Comment by InoMurko** [comment]
From what I've seen, 0.3 is not stable. Try 0.2.1!

**Comment by seamon** [comment]
@InoMurko that's right, 0.2.2 is good, we're using it now. hope the new version released soon

thank you so much.

**Comment by InoMurko** [comment]
@seamon can you leave the issue open? I think it's still an issue worth addressing in version 0.3!
Thanks.

**Comment by seamon** [comment]
@InoMurko sure, i reopened it. hope it helps.

thanks again ^_^

**Comment by vbaranov** [comment]
@seamon Fixed in master branch.
