### ISSUE TITLE
Uning array of complex types

### ISSUE THREAD

**Issue by steffenix** [poanetwork/ex_abi#44]
I am trying to use the ABI with the https://github.com/makerdao/multicall contract.

`aggregate(Call[] memory calls)`

```
    struct Call {
        address target;
        bytes callData;
    }
```

So I am using the encode function with `aggregate((address,bytes)[])`

I am getting the following error:

```
        # 1
        {:tuple, [:address, :bytes]}
        # 2
        <<238, 251, 161, 230, 57, 5, 239, 29, 122, 203, 165, 168, 81, 60, 112, 48, 124, 28, 228, 65>>
        # 3
        []
        # 4
        []
```

I have also tried to do:

```
      function = %ABI.FunctionSelector{
        function: "aggregate",
        input_names: ["calls"],
        type: :function,
        types: [array: {:tuple, [:address, :bytes]}]
      }
    ABI.encode(function, values)
```

The issue is the binary isn't passing the Kernel.is_tupple condition.

The second parameter passed to the function is:
```
[
[address, data]
]
```

**Comment by steffenix** [comment]
I see OMG is doing something similar with the version 0.4 of the library, https://github.com/omgnetwork/omg-childchain-v1/blob/0867eba533ba461210cb4dc99b168343ed0f9f9f/apps/omg_eth/lib/omg_eth/root_chain/abi_function_selector.ex#L217

**Comment by steffenix** [comment]
What I ended up doing is add the array inside an array, indeed the second parameter is an array of arguments.

**Comment by sheehan1102** [comment]
@steffenix can you show your working solution? I'm having same issue.

**Comment by steffenix** [comment]
Are you sure you are using the library properly?
The parameters should be an array

**Comment by sheehan1102** [comment]
@steffenix I'm assuming I'm not, because it is not working.

Here is example code:

```
params = Enum.map(assets, fn asset ->
  [asset.address, "balanceOf(address)"]
end)

abi =
  ABI.encode("aggregate((address,bytes)[])", params)
```

Params are an array.

I receive the same error as you did above, since the first param coming into `do_encode_type` does not match any function clause.

**Comment by steffenix** [comment]
Can't help with more code but I would look at the address format check the examples they need to be decoded
