### ISSUE TITLE
Problem Decoding input 

### ISSUE THREAD

**Issue by wallbanger1** [poanetwork/ex_abi#45]
As a test, I am trying to decode input from this txn: https://etherscan.io/tx/0x5b5e8bef3fe643a2cd57dcb4fd4985aeeed87b1b78b7d2844a72d58b759f645a

I am pretty sure I have the proper signature and abi, data etc:
![image](https://user-images.githubusercontent.com/71581829/97104140-be4f1700-166e-11eb-9019-fc0b110bfd49.png)

The input data is:
```
0x7ff36ab5000000000000000000000000000000000000000000000000050988c69102478c000000000000000000000000000000000000000000000000000000000000008000000000000000000000000038f7c6dc001ed4c5c163be7ed8de76e7b5e32490000000000000000000000000000000000000000000000000000000005f70ce010000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000cc4304a31d09258b0029ea7fe63d032f52e44efe
```

The function signature is: `swapExactETHForTokens(uint256,address[],address,uint256)`

I am trying to use it like:
```
iex(2)> decoded_string = "7ff36ab5000000000000000000000000000000000000000000000000050988c69102478c000000000000000000000000000000000000000000000000000000000000008000000000000000000000000038f7c6dc001ed4c5c163be7ed8de76e7b5e32490000000000000000000000000000000000000000000000000000000005f70ce010000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000cc4304a31d09258b0029ea7fe63d032f52e44efe" |> Base.decode16!(case: :lower)
output: <<127, 243, 106, 181, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 5, 9, 136, 198, 145, 2, 71, 140, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, ...>>
```

The command:
```
iex(3)> ABI.decode("swapExactETHForTokens(uint256,address[],address,uint256)", decoded_string)
```
gives me an error:

```
** (MatchError) no match of right hand side value: <<127, 243, 106, 181, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 9, 136, 198, 145, 2, 71, 140, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>
    (ex_abi 0.5.1) lib/abi/type_decoder.ex:299: ABI.TypeDecoder.decode_type/3
    (ex_abi 0.5.1) lib/abi/type_decoder.ex:180: anonymous fn/3 in ABI.TypeDecoder.do_decode_raw/2
    (elixir 1.11.0) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_abi 0.5.1) lib/abi/type_decoder.ex:177: ABI.TypeDecoder.do_decode_raw/2
    (ex_abi 0.5.1) lib/abi/type_decoder.ex:171: ABI.TypeDecoder.decode_raw/2
```

I'm not sure what I am doing wrong but if it's something obvious please let me know.
Thanks!

**Comment by wallbanger1** [comment]
The main issue seems to be that the first 4 bytes containing the method sig wasn't being peeled off and so I was feeding bad binary data to the decoder. After removing the function sig manually the decoder no longer throws an error. I think I am on the right track now.
![image](https://user-images.githubusercontent.com/71581829/97104671-fbb5a380-1672-11eb-917a-6d90c57d7bac.png)

**Comment by ayrat555** [comment]
@wallbanger1 you're right. passing a raw string signature requires encoded data without signature id.
Another option is to pass `FunctionSelector` struct, in this case, it accepts encoded data with signature id
