### ISSUE TITLE
Inconsistency in enconde/decode address?

### ISSUE THREAD

**Issue by aherranz** [poanetwork/ex_abi#48]
I think that adresses are encoded as uin160 (ABI.TypeEncoder.do_encode_type) but are decoded as binary (ABI.TypeDecoder.decode_type). This looks like inconsistent. Am I wrong?

**Comment by ayrat555** [comment]
It seems ok. Each test in ex_abi  encodes and decodes data to make sure that the logic is consistent :
https://github.com/poanetwork/ex_abi/blob/master/test/abi/type_encoder_test.exs#L150
