### ISSUE TITLE
Support for `error` selectors

### ISSUE THREAD

**Issue by nikitosing** [poanetwork/ex_abi#68]
I think it will be useful to add support of errors which were recently included in solidity.
https://docs.soliditylang.org/en/latest/abi-spec.html#errors 

example of such entry: 
`[{"inputs", [%{"internalType" => "address", "name" => "addr", "type" => "address"}, %{"internalType" => "uint256", "name" => "balance", "type" => "uint256"}]}, {"name", "SomeCustomError"}, {"type", "error"}]`
@ayrat555

**Comment by ayrat555** [comment]
@nikitosing hello! can you please verify if https://github.com/poanetwork/ex_abi/pull/69 is what you need
