### ISSUE TITLE
question/comments regarding names

### ISSUE THREAD

**Issue by gregors** [poanetwork/ex_abi#77]
This is a question to gain some further understanding on my part.

```elixir
[
  %{
    "inputs" => [],
    "name" => "getItems",
    "outputs" => [
      %{
        "components" => [
          %{"internalType" => "uint256", "name" => "price", "type" => "uint256"},
          %{
            "internalType" => "uint256",
            "name" => "itemId",
            "type" => "uint256"
          }
        ],
        "internalType" => "struct StructTester.Item[]",
        "name" => "",
        "type" => "tuple[]"
      }
    ],
    "stateMutability" => "view",
    "type" => "function"
  }
]

# running through ABI.parse_specification we get

[
  %ABI.FunctionSelector{
    function: "getItems",
    input_names: [],
    inputs_indexed: nil,
    method_id: <<65, 13, 89, 204>>,
    returns: [array: {:tuple, [uint: 256, uint: 256]}],
    type: :function,
    types: []
  }
]
```

Since the outputs had a component with names (price and itemId) for the internal struct should there be an `output_names` list in addition to `input_names`? Would that list have those internal names? Or could we add another field that looks up components? The end goal for me is to unwrap the tuple into a key/value pair.

**Comment by ayrat555** [comment]
@gregors hello. I'm sorry for a late reply

`input_names` are used for event decoding.

I think we could add `output_names` but currently this field it's not used in the ex_abi. Because it returns a list of decoded data, not a data structure.
