### ISSUE TITLE
could not compile dependency :ex_keccak, "mix compile" failed

### ISSUE THREAD

**Issue by somoza** [poanetwork/ex_abi#83]
** (ErlangError) Erlang error: :enoent
    (elixir 1.13.0) lib/system.ex:1044: System.cmd("cargo", ["metadata", "--format-version=1"], [cd: "native/exkeccak"])
    (rustler 0.23.0) lib/rustler/compiler/config.ex:81: Rustler.Compiler.Config.external_resources/2
    (rustler 0.23.0) lib/rustler/compiler/config.ex:69: Rustler.Compiler.Config.build/1
    (rustler 0.23.0) lib/rustler/compiler.ex:9: Rustler.Compiler.compile_crate/2
    lib/ex_keccak.ex:6: (module)
could not compile dependency :ex_keccak, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile ex_keccak", update it with "mix deps.update ex_keccak" or clean it with "mix deps.clean ex_keccak"

**Comment by ayrat555** [comment]
@somoza hello. ex_abi requires Rust. Cargo is the Rust package manager.

do you have it on your machine?

**Comment by somoza** [comment]
The problem was with the Rust installator. Solution posted here: https://github.com/blockscout/blockscout/issues/5100
